export const colors = {
  primary: '#00cdcd',
  inactive: '#6dd0d0',
  text: '#000',
  textReverse: '#FFF',
  // tabBar: "#222326",
  tabBar: '#00cdcd',
  itemInactive: "#d4d8db",
  itemActive: '#FFF',
  // background: "#121212",
  background: '#FFF',
  white: "#FFFFFF",
  darkWhite: "#FDFDFD",
  green: "#1DB954",
  lightGrey: "#CBCBCC",
  grey: "#B9B9B9",
  darkGrey: "#A8A8A9",
  darkerGrey: "#505153",
}
